# Generated by Django 5.1.5 on 2025-01-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0002_rename_music_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
