# Generated by Django 5.1.5 on 2025-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0003_alter_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
