# Generated by Django 5.1.5 on 2025-01-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='published_date',
            new_name='created_date',
        ),
    ]
