# Generated by Django 5.1.5 on 2025-02-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0008_rename_author_song_artist_remove_song_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
