# Generated by Django 5.1.5 on 2025-02-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0009_rename_content_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
